title: Wandering Notes
description: Travel notes, one place at a time.
url: "https://cedric-c.github.io"
baseurl: "/travel"

theme: minima
lang: en

header_pages:
  - about.md

markdown: kramdown
permalink: /:year/:month/:day/:title/
